from __future__ import annotations
import os, json, base64, textwrap
from typing import Dict, Any
from github import Github

def generate_scaffold(topic: str) -> Dict[str, Any]:
    files = {
        "README.md": f"""# Starter: {topic}

This scaffold was generated by the Agentic Research Assistant.

## What you get
- minimal PyTorch training loop
- environment.yml and Dockerfile
- placeholder dataset loader
""".strip(),
        "environment.yml": textwrap.dedent("""
            name: agent-research
            channels: [conda-forge, pytorch]
            dependencies:
              - python=3.11
              - pytorch
              - cudatoolkit
              - pip
              - pip:
                - numpy
                - pandas
                - scikit-learn
        """),
        "src/train.py": textwrap.dedent("""
            import torch, time

            def train():
                # TODO: replace with real dataset & model
                x = torch.randn(128, 32)
                w = torch.randn(32, 1, requires_grad=True)
                y = x @ w + 0.1 * torch.randn(128, 1)
                opt = torch.optim.SGD([w], lr=1e-2)
                for step in range(200):
                    opt.zero_grad()
                    loss = ((x @ w - y) ** 2).mean()
                    loss.backward()
                    opt.step()
                    if step % 20 == 0:
                        print(f"step={step} loss={loss.item():.4f}")
                print("done")
            if __name__ == "__main__":
                train()
        """),
        "Dockerfile": textwrap.dedent("""
            FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
            WORKDIR /app
            COPY . .
            RUN pip install -r requirements.txt || true
            CMD ["python", "src/train.py"]
        """),
        ".gitignore": textwrap.dedent("""
            __pycache__/
            .venv/
            .env
            .DS_Store
        """),
        "requirements.txt": "torch"
    }
    return {"type": "scaffold", "files": files}

def append_artifact(current_json: str, artifact: Dict[str, Any]) -> str:
    import json
    arr = json.loads(current_json or "[]")
    arr.append(artifact)
    return json.dumps(arr)

def commit_scaffold(scaffold_env=None) -> str:
    token = os.getenv("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN not set; cannot create repo.")
    gh = Github(token)
    user = gh.get_user()
    repo = user.create_repo("agentic-research-starter", private=True)
    # find scaffold in env / or create a default one
    scaffold = generate_scaffold("Agentic RL Research")
    for path, content in scaffold["files"].items():
        repo.create_file(path, "init", content, branch="main")
    return repo.html_url
